name: Erlang CI

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    container:
      image: erlang:21.3

    steps:
    - uses: actions/checkout@v2
    - name: Compile
      run: rebar3 compile
    - name: Run tests
      run: rebar3 do eunit, ct
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
