name: Erlang CI

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    container:
      image: erlang:21.3

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - name: Get deps
      run: rebar3 get-deps
    - name: Compile
      run: rebar3 compile xref
    - name: Run tests
      run: rebar3 eunit
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
