name: Erlang CI

on: [push, pull_request]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest

    container:
      image: erlang:21.3

    steps:
    - uses: actions/checkout@v2
    - name: Install
      run: rebar get-deps
    - name: Compile
      run: rebar compile xref
    - name: Run tests
      run: rebar skip_deps=true eunit
    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
